#!/usr/bin/env python3

"""
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""


import pe_utils


def even_fib(lim):
    s = 0
    i = 0
    j = 1
    while i < lim:
        if i % 2 == 0:
            s += i
        i, j = next_fib(i, j)
    return s


def next_fib(i, j):
    """
    Receives pair of fib numbers
    and returns them shifted.
    """
    return j, j + i


pe_utils.test(even_fib, [4000000], 4613732)

