#!/usr/bin/env python3

"""
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""


import time


def even_fib():
    s = 0
    i = 0
    j = 1
    while i < 4000000:
        if i % 2 == 0:
            s += i
        i, j = next_fib(i, j)
    return s


def next_fib(i, j):
    """
    Receives pair of fib numbers
    and returns them shifted.
    """
    return j, j + i


def time_and_print(func):
    """
    Call function, time its execution
    and print results.
    """
    GREEN = "\033[92m"
    RED = "\033[0;31m"
    END = "\033[0m"
    t1 = time.process_time()
    res = func()
    t2 = time.process_time() - t1
    print(func.__name__)
    print("    Result:", GREEN, res, END, "time:", t2)


time_and_print(even_fib)

