#!/usr/bin/env python3

"""
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""


import pe_utils


def problem1(limit):
    gen = pe_utils.fibonacci_generator()
    result = 0
    x = next(gen)
    while x < limit:
        if x % 2 == 0:
            result += x
        x = next(gen)
    return result


pe_utils.test(problem1, [4000000], 4613732)

