#!/usr/bin/env python3

"""
Problem 12

The sequence of triangle numbers is generated by adding the natural numbers. So
the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten
terms would be:
    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:
     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred
divisors?
"""


import pe_utils


def triangle_numbers_generator():
    acc = 0
    curr = 1
    while True:
        acc += curr
        yield acc
        curr += 1


def problem12(n):
    triangle_numbers = triangle_numbers_generator()
    divisors = 0
    while divisors < n:
        number = next(triangle_numbers)
        divisors = len(pe_utils.divisors(number))
    return number


triangle_numbers = triangle_numbers_generator()
pe_utils.test(next, [triangle_numbers], 1)
pe_utils.test(next, [triangle_numbers], 3)
pe_utils.test(next, [triangle_numbers], 6)
pe_utils.test(next, [triangle_numbers], 10)
pe_utils.test(next, [triangle_numbers], 15)
pe_utils.test(next, [triangle_numbers], 21)


pe_utils.test(problem12, [500], 76576500)

